Document: automoc
Title: Debian automoc Manual
Author: <insert document author here>
Abstract: This manual describes what automoc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/automoc/automoc.sgml.gz

Format: postscript
Files: /usr/share/doc/automoc/automoc.ps.gz

Format: text
Files: /usr/share/doc/automoc/automoc.text.gz

Format: HTML
Index: /usr/share/doc/automoc/html/index.html
Files: /usr/share/doc/automoc/html/*.html
